<?php
use cAc\GcsWrapper, Google\Cloud\ServiceBuilder;
$b = '';
$p = '';
$a = '';
$result = null;

if( isset( $_POST['submit'] ) && "Submit" === $_POST['submit'] ) {
	
	if( isset( $_POST['projectid'] ) && isset( $_POST['bucketid'] ) && isset( $_POST['jsonkey'] ) ) {
	
		$b = $_POST['bucketid'];
		$p = $_POST['projectid'];
		$a = isset( $_POST['action'] ) ? $_POST['action'] : '';
		require_once( __DIR__ . '/GcsWrapper.php' );
		$storage_test = new cAc\GcsWrapper\GoogleCloudStorage( $p, $_POST['jsonkey'], $b );	
		switch( $a ) {
			
			case 1:
				break;
			case 2:
				if( isset( $_POST['aclEntityType'] ) && isset( $_POST['aclEntityValue'] ) && isset( $_POST['aclRole'] ) ) {
					$entity = $_POST['aclEntityType'] . $_POST['aclEntityValue'];
					$role = $_POST['aclRole'];
					$result = $storage_test->bucket_acl_entity_add( $entity, $role );
				}
				break;
			case 3:
				if( isset( $_POST['aclEntityType'] ) && isset( $_POST['aclEntityValue'] ) ) {
					$entity = $_POST['aclEntityType'] . $_POST['aclEntityValue'];
					$storage_test->bucket_acl_entity_remove( $entity );
				}
				break;
		
		}
	
	}

}
?>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="js/test.js"></script>

<header class="container">
<h1>GCS Wrapper Test</h1>
<p>Enter the Project ID, Bucket ID, and content of the json file generated by Google's IAM, then submit to get results</p>
</header>
<content class="container">
	<form id="gcs-test-form" class="form-horizontal" method="post">

		<fieldset>

		<!-- Form Name -->
		<legend>Test GCS</legend>

		<!-- Text input-->
		<div class="form-group">
		  <label class="col-md-4 control-label" for="projectid">Project ID</label>  
		  <div class="col-md-4">
		  <input id="projectid" name="projectid" type="text" placeholder="project-12345" class="form-control input-md" <?php echo empty( $p ) ? '' : 'value="' . $p . '"'?> >
		  <span class="help-block">enter the id, not the name</span>  
		  </div>
		</div>

		<!-- Text input-->
		<div class="form-group">
		  <label class="col-md-4 control-label" for="bucketid">Bucket ID</label>  
		  <div class="col-md-4">
		  <input id="bucketid" name="bucketid" type="text" placeholder="your-bucket-id" class="form-control input-md" <?php echo empty( $b ) ? '' : 'value="' . $b . '"'?> >
		  <span class="help-block">enter the unique identifier for the bucket</span>  
		  </div>
		</div>

		<!-- Textarea -->
		<div class="form-group">
		  <label class="col-md-4 control-label" for="jsonkey">JSON Key Content</label>
		  <div class="col-md-4">                     
			<textarea class="form-control" id="jsonkey" name="jsonkey"><?php echo isset( $_POST['jsonkey'] ) ? $_POST['jsonkey'] : '' ?></textarea>
		  </div>
		</div>
		
		<!-- Select Basic -->
		<div id="action-select" class="form-group">
		  <label class="col-md-4 control-label" for="action">Select an Operation</label>
		  <div class="col-md-4">
			<select id="action" name="action" class="form-control">
			  <option value="1">Generate Object Only</option>
			  <option value="2">Add ACL entity to bucket</option>
			  <option value="3">Remove ACL entity from bucket</option>
			</select>
		  </div>
		</div>

		
		<div class="form-group">
		  <div class="col-md-4 col-md-offset-4">                     
			<input type="submit" class="form-control btn btn-primary" id="submit" name="submit" value="Submit"/>
		  </div>
		</div>

		</fieldset>

	</form>
	<div class="row">
		<div id="post-values" class="col-md-6 col-md-offset-3">
			<h2>Project: <?php echo $p ?></h2>
			<h2>Bucket: <?php echo $b ?></h2>
			<h2>Operation<?php echo $a ?></h2>
		</div>
	</div>
	<div class="row">
                <div id="post-values" class="col-md-6 col-md-offset-3">
                        <h2><button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#showObject" aria-expanded="false" aria-controls="collapseExample">Full Object Output</button></h2>
                        <p id="showObject" class="collapse"><?php print_r( $storage_test ) ?></p>
                </div>
        </div>
</content>
<footer class="container">
	<div class="result">
		<?php
		if (!empty( $result ) {
		
			echo '<h2>Result:</h2>';
			print_r( $result );
		
		}
		?>
	</div>
	<div class="errors">
		<?php
		if( isset( $storage_test ) ) {
			
			echo '<h2>Errors:</h2>';
			print_r( $storage_test->errors );
		
		}
		?>
	</div>
</footer>
